version: '3.4'

volumes:
  prometheus-data:

services:
  phonebook:
    image: phonebook-image
    build:
      context: .
      dockerfile: src/Phonebook/Dockerfile
    expose:
      - "5000"
  nginxphonebook:
    image: nginxphonebook-image
    build:
        context: .
        dockerfile: src/nginx/Dockerfile
    depends_on:
      - phonebook
    ports:
        - "90:80"
  prometheus:
    image: prometheusphonebook-image
    build:
        context: .
        dockerfile: src/Prometheus/Dockerfile
    volumes:
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=/prometheus/
      - --web.route-prefix=/
    depends_on:
      - phonebook
    expose:
      - "9090"
