version: '3.4'

services:
  phonebook:
    image: phonebook-image
    build:
      context: .
      dockerfile: src/Phonebook/Dockerfile
    expose:
      - "5000"
  nginxphonebook:
    image: nginxphonebook-image
    build:
        context: .
        dockerfile: src/nginx/Dockerfile
    depends_on:
      - phonebook
    ports:
        - "90:80"
  prometheusphonebook:
    image: prometheusphonebook-image
    build:
        context: .
        dockerfile: src/Prometheus/Dockerfile
    depends_on:
      - phonebook
    ports:
      - "9090:9090"