version: '3.4'

services:
  phonebook:
    image: phonebook
    build:
      context: .
      dockerfile: src/Phonebook/Dockerfile
    ports:
      - 80:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  nginx:
    image: nginx-image
    build:
        context: .
        dockerfile: src/nginx/Dockerfile
    depends_on:
      - phonebook
    ports:
        - "90:80"
